name: Lint

on: [ push,workflow_dispatch ]

jobs:
  golang_ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.20

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Commit back
        if: ${{ github.repository_owner == 'foxwhite25' && !github.event.pull_request }}
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git commit -m "ci(chore): Fix stylings"
          git push

      - name: Suggester
        if: ${{ github.event.pull_request }}
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: golangci-lint
